apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sins1
  namespace: default
spec:
  clusterServiceClassExternalName: github-repo
  clusterServicePlanExternalName: public
  externalID: simple
  authInfo:
        basic:
            secretRef:
                name: bsec
                namespace: default